# Generated by Django 3.1.5 on 2021-01-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.TextField(default='')),
                ('Email', models.TextField(default='')),
                ('Username', models.TextField(default='')),
                ('Password', models.TextField(default='')),
                ('Image', models.ImageField(default='Health_Professional/dummy.jpg', upload_to='Signup/')),
                ('Sender_ID', models.TextField(default='')),
                ('Device_type', models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('web', 'web')], default='android', max_length=100)),
            ],
        ),
    ]
